image: oven/bun:latest

cache:
  paths:
    - node_modules/
    - .svelte-kit/

before_script:
  - bun install

lint:
  script:
    - bun run lint

build:
  script:
    - bun run build
  artifacts:
    paths:
      - node_modules/
      - .svelte-kit/

