services:
  friendly_back:
    container_name: friendly_back
    image: friendly_backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/friendly
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - mongo
  friendly_front:
    container_name: friendly_front
    image: friendly_front:latest
    ports:
      - "5173:5173"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    depends_on:
      - friendly_back
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
